image: laravelsail/php84-composer:latest

pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - composer
          script:
            # Install Xdebug for code coverage
            - pecl install xdebug >/dev/null 2>&1 || echo "Failed to install Xdebug"
            - docker-php-ext-enable xdebug >/dev/null 2>&1 || echo "Failed to enable Xdebug"
            - echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

            # Install Composer dependencies
            - COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --prefer-dist --optimize-autoloader

            # Run tests
            - |
              php -d memory_limit=-1 ./vendor/bin/pest --coverage --parallel --stop-on-failure
